//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelIntegratedComputerSystems.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HicsTestDbEntities1 : DbContext
    {
        public HicsTestDbEntities1()
            : base("name=HicsTestDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeShift> EmployeeShifts { get; set; }
        public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
        public virtual DbSet<ExpenseType> ExpenseTypes { get; set; }
        public virtual DbSet<HouseKeepingStatu> HouseKeepingStatus { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<SecurityRank> SecurityRanks { get; set; }
        public virtual DbSet<MaintenanceLogs> MaintenanceLogs { get; set; }
        public virtual DbSet<MaintenanceTypes> MaintenanceTypes { get; set; }
        public virtual DbSet<RoomStatus> RoomStatus { get; set; }

        public System.Data.Entity.DbSet<HotelIntegratedComputerSystems.Services.Admin.EmployeeTypeViewModel> EmployeeTypeViewModels { get; set; }

        public System.Data.Entity.DbSet<HotelIntegratedComputerSystems.Models.Admin.EmployeeViewModel> EmployeeViewModels { get; set; }
    }
}
